#!/usr/bin/env python3
"""Tests for derive_plugin_ui_sdk.py — the QGroundControl.PluginUI SDK derivation."""

from __future__ import annotations

import pytest
from derive_plugin_ui_sdk import carve_qmltypes, parse_qmldir, render_sdk_qmldir

ROSTER = """\
# Header comment, dropped from the derived file.
module QGroundControl.PluginUI

depends QtQuick

# --- frozen tier ---
QGCLabel 1.0 ../Controls/QGCLabel.qml
singleton ScreenTools 1.0 ../Controls/ScreenTools.qml

# --- unstable tier ---
MapFitFunctions 1.0 ../FlightMap/Widgets/MapFitFunctions.qml
"""

QMLTYPES = """\
import QtQuick.tooling 1.2

// This file was auto-generated by qmltyperegistrar.

Module {
    Component {
        file: "Other.h"
        name: "Other"
        exports: ["QGC/Other 1.0"]
    }
    Component {
        file: "QGCPalette.h"
        name: "QGCPalette"
        exports: ["QGC/QGCPalette 1.0"]
        Property { name: "window"; type: "QColor" }
    }
}
"""


def test_parses_every_type_entry():
    qmldir = parse_qmldir(ROSTER)

    assert qmldir.module == "QGroundControl.PluginUI"
    assert [e.name for e in qmldir.entries] == ["QGCLabel", "ScreenTools", "MapFitFunctions"]
    assert [e.singleton for e in qmldir.entries] == [False, True, False]
    assert qmldir.entries[0].path == "../Controls/QGCLabel.qml"
    assert qmldir.entries[0].filename == "QGCLabel.qml"


@pytest.mark.parametrize(
    "text,message",
    [
        ("depends QtQuick\nmodule Foo\n", "before the 'module'"),
        ("module Foo\nQGCLabel ../Controls/QGCLabel.qml\n", "not a type entry"),
        ("module Foo\nQGCLabel one ../Controls/QGCLabel.qml\n", "bad version"),
        ("# comments only, no roster at all\n", "no 'module' directive"),
        ("module Foo\nmodule Bar\n", "duplicate 'module'"),
    ],
)
def test_rejects_malformed_roster(text, message):
    # Silently dropping a roster line would publish a smaller contract than the
    # one the file declares, so every unaccounted-for line is fatal.
    with pytest.raises(ValueError, match=message):
        parse_qmldir(text)


def test_rejects_a_basename_collision_across_source_dirs():
    # The package flattens every body into one directory. Two entries sharing a
    # filename would install one body under both type names — a published type
    # silently shipping the wrong QML.
    colliding = ROSTER + "OtherLabel 1.0 ../PlanView/QGCLabel.qml\n"

    with pytest.raises(ValueError, match=r"duplicate filename.*QGCLabel\.qml"):
        parse_qmldir(colliding)


def test_rejects_a_duplicate_type_name():
    with pytest.raises(ValueError, match=r"duplicate type name.*QGCLabel"):
        parse_qmldir(ROSTER + "QGCLabel 1.0 ../PlanView/Something.qml\n")


def test_sdk_qmldir_does_not_duplicate_a_roster_typeinfo_line():
    rendered = render_sdk_qmldir(
        parse_qmldir(ROSTER.replace("depends QtQuick", "typeinfo Stale.qmltypes\ndepends QtQuick")),
        "QGroundControl.PluginUI.qmltypes",
    )

    assert rendered.count("typeinfo ") == 1
    assert "Stale.qmltypes" not in rendered


def test_sdk_qmldir_flattens_paths_and_keeps_tiers():
    rendered = render_sdk_qmldir(parse_qmldir(ROSTER), "QGroundControl.PluginUI.qmltypes")

    assert "QGCLabel 1.0 QGCLabel.qml" in rendered
    assert "singleton ScreenTools 1.0 ScreenTools.qml" in rendered
    assert "MapFitFunctions 1.0 MapFitFunctions.qml" in rendered
    assert "../Controls/" not in rendered
    # Directives survive; tier comments survive; the roster's own header does not.
    assert "depends QtQuick" in rendered
    assert "# --- frozen tier ---" in rendered
    assert "# --- unstable tier ---" in rendered
    assert "Header comment" not in rendered
    # typeinfo goes immediately after module so the C++ half is discoverable.
    lines = [line for line in rendered.splitlines() if line.strip()]
    module_index = lines.index("module QGroundControl.PluginUI")
    assert lines[module_index + 1] == "typeinfo QGroundControl.PluginUI.qmltypes"


def test_carve_keeps_only_requested_types_and_retargets_exports():
    carved = carve_qmltypes(QMLTYPES, ["QGCPalette"], "QGroundControl.PluginUI")

    assert 'name: "QGCPalette"' in carved
    assert 'name: "Other"' not in carved
    assert 'exports: ["QGroundControl.PluginUI/QGCPalette 1.0"]' in carved
    assert carved.startswith("import QtQuick.tooling 1.2")
    assert carved.count("Module {") == 1
    # Property metadata is what the whole file is for.
    assert 'name: "window"' in carved


def test_carve_preserves_requested_order():
    two_types = QMLTYPES.replace('name: "Other"', 'name: "PlanMasterController"').replace(
        '"QGC/Other 1.0"', '"QGC/PlanMasterController 1.0"'
    )
    carved = carve_qmltypes(two_types, ["QGCPalette", "PlanMasterController"], "URI")

    assert carved.index('name: "QGCPalette"') < carved.index('name: "PlanMasterController"')


def test_carve_survives_braces_inside_strings():
    tricky = QMLTYPES.replace(
        'Property { name: "window"; type: "QColor" }',
        'Property { name: "window"; type: "QColor" }\n        Property { name: "tip"; type: "QString"; '
        'defaultValue: "a { brace" }',
    )
    carved = carve_qmltypes(tricky, ["QGCPalette"], "URI")

    # A naive brace count would truncate the component at the literal.
    assert 'name: "tip"' in carved
    assert carved.rstrip().endswith("}")


def test_carve_rewrites_only_the_exports_line():
    decoy = QMLTYPES.replace(
        'Property { name: "window"; type: "QColor" }',
        'Property { name: "hint"; type: "QString"; defaultValue: "QGC/Fake 1.0" }',
    )
    carved = carve_qmltypes(decoy, ["QGCPalette"], "URI")

    assert 'exports: ["URI/QGCPalette 1.0"]' in carved
    assert 'defaultValue: "QGC/Fake 1.0"' in carved


def test_carve_reports_a_missing_type():
    # A type registered in C++ but absent from the generated metadata would ship a
    # qmldir promising something the package cannot describe.
    with pytest.raises(ValueError, match="NotAType"):
        carve_qmltypes(QMLTYPES, ["QGCPalette", "NotAType"], "URI")
