# ============================================================================
# QGroundControl Plugin Helper Functions
# ============================================================================

#[=======================================================================[.rst:
qgc_add_plugin
--------------

Single entry point for building a QGroundControl plugin. Configures the
plugin as a MODULE library, wires up its manifest, generates a per-build
marker symbol (qgcPluginBuildMarker, resolved at runtime from the mapped
image), and auto-deploys the built library to the host's runtime plugin
search path for the dev loop. TIER SDK links only the published QGCPluginAPI
+ Qt (D2's include boundary) — the only supported linkage.

Example usage:
  qgc_add_plugin(MyPlugin
      TIER SDK
      MANIFEST qgcplugin.json.in
      SOURCES
          MyPlugin.h
          MyPlugin.cc
      QRC_FILES
          MyPlugin.qrc
  )

Plugin-specific extras (extra Qt modules, extra include dirs, test
subdirectories, ...) are added by the caller with normal CMake commands
after calling qgc_add_plugin().

Pass NO_DEPLOY to skip the runtime auto-deploy step — for build-only fixtures
(e.g. test dylibs) that must never land in the real runtime plugin directory.

#]=======================================================================]

function(qgc_add_plugin PLUGIN_NAME)
    set(options NO_DEPLOY)
    set(oneValueArgs TIER MANIFEST)
    set(multiValueArgs SOURCES QRC_FILES)
    cmake_parse_arguments(PLUGIN "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT PLUGIN_TIER STREQUAL "SDK")
        message(FATAL_ERROR
            "qgc_add_plugin(${PLUGIN_NAME}): TIER ${PLUGIN_TIER} is not supported yet. "
            "SDK works today; QML is not implemented yet.")
    endif()

    if(NOT PLUGIN_MANIFEST)
        message(FATAL_ERROR "qgc_add_plugin(${PLUGIN_NAME}): MANIFEST is required.")
    endif()

    # Build marker: a timestamp+random value baked into an exported extern "C"
    # symbol, read at runtime via QLibrary::resolve() against the mapped image
    # (never the file) so the host can tell two builds of the same plugin
    # id/version apart — the observable this unit exists to provide
    # (plugin-enable-disable-correctness U1, Pillar 4).
    #
    # The marker must differ whenever the linked dylib differs, so it is the
    # OUTPUT of an ordinary custom command whose DEPENDS are the real files that
    # produce that dylib. An OUTPUT-producing command is ordered before the
    # compile of its own output by construction, so the string inside the linked
    # binary is always this build's — and a dylib that did not change keeps its
    # marker, which is the honest answer rather than churn.
    #
    # Three mechanisms were tried here and are WRONG — do not reintroduce them:
    #   * file(WRITE) alone runs only at configure time, so an incremental build
    #     that recompiles changed sources without touching CMakeLists.txt relinks
    #     new code against a stale marker object.
    #   * add_custom_command(TARGET ... PRE_BUILD) is silently remapped to
    #     PRE_LINK by every generator except Visual Studio, so it runs AFTER the
    #     marker .cc was compiled — the embedded value sits one build cycle
    #     behind, permanently and invisibly.
    #   * a phony always-dirty target named in DEPENDS is emitted by CMake as an
    #     order-only (`||`) prerequisite: it orders the edge but never makes it
    #     run, so the command simply stops firing after the first build.
    # Q_DECL_EXPORT, not QGCPLUGINAPI_EXPORT: the latter resolves to Q_DECL_IMPORT
    # outside the SDK target, which is __declspec(dllimport) on a definition on
    # Windows — a compile error there, and merely harmless on ELF/Mach-O where it
    # still yields default visibility. This symbol is only ever exported *from* a
    # plugin. Depending on QtGlobal alone also keeps the generated TU free of any
    # SDK include path.
    set(_qgc_plugin_marker_file "${CMAKE_CURRENT_BINARY_DIR}/${PLUGIN_NAME}_BuildMarker.cc")
    set(_qgc_plugin_marker_script "${CMAKE_CURRENT_BINARY_DIR}/${PLUGIN_NAME}_GenerateBuildMarker.cmake")
    string(CONCAT _qgc_plugin_marker_script_content
        "string(TIMESTAMP _ts \"%Y%m%d%H%M%S\")\n"
        "string(RANDOM LENGTH 16 _rand)\n"
        "file(WRITE \"${_qgc_plugin_marker_file}\"\n"
        "    \"// Generated by qgc_add_plugin(). Do not edit.\\n\"\n"
        "    \"#include <QtCore/QtGlobal>\\n\"\n"
        "    \"extern \\\"C\\\" Q_DECL_EXPORT const char* qgcPluginBuildMarker() {\\n\"\n"
        "    \"    return \\\"\${_ts}-\${_rand}\\\";\\n\"\n"
        "    \"}\\n\"\n"
        ")\n"
    )
    # Written only when the content actually differs. A bare file(WRITE) always
    # touches the file, and since the script is a marker dependency below, that
    # would relink every plugin on every reconfigure.
    set(_qgc_plugin_marker_script_stale TRUE)
    if(EXISTS "${_qgc_plugin_marker_script}")
        file(READ "${_qgc_plugin_marker_script}" _qgc_plugin_marker_script_existing)
        if(_qgc_plugin_marker_script_existing STREQUAL _qgc_plugin_marker_script_content)
            set(_qgc_plugin_marker_script_stale FALSE)
        endif()
    endif()
    if(_qgc_plugin_marker_script_stale)
        file(WRITE "${_qgc_plugin_marker_script}" "${_qgc_plugin_marker_script_content}")
    endif()
    # Anything whose change yields a different dylib must also yield a different
    # marker: this plugin's own sources and resources, its manifest, and the SDK
    # it links. The SDK goes in as a FILE ($<TARGET_FILE:...>) rather than a
    # target name, because a target name in DEPENDS is order-only and would not
    # trigger regeneration — the trap the third bullet above describes.
    #
    # $<TARGET_FILE:QGCPluginAPI> alone is NOT enough to cover the SDK: it only
    # moves when the SDK dylib relinks, and QGCPluginInterface.h has no backing
    # .cc in that library, so editing it — the file carrying
    # QGC_PLUGIN_API_VERSION_MAJOR, the most ABI-relevant content there is —
    # recompiles every plugin without relinking the SDK. The public header set
    # therefore goes in explicitly, reusing the one list src/PluginAPI already
    # keeps so a header added to the SDK surface is covered automatically.
    if(NOT QGC_PLUGIN_API_PUBLIC_HEADERS)
        message(FATAL_ERROR
            "qgc_add_plugin(${PLUGIN_NAME}): QGC_PLUGIN_API_PUBLIC_HEADERS is empty. "
            "The build marker would silently stop tracking SDK header changes.")
    endif()
    list(TRANSFORM QGC_PLUGIN_API_PUBLIC_HEADERS PREPEND "${CMAKE_SOURCE_DIR}/src/PluginAPI/"
        OUTPUT_VARIABLE _qgc_plugin_marker_sdk_headers
    )
    # The generator script itself is a dependency: changing how the marker is
    # emitted must regenerate it, or a fix to the generated code sits unapplied
    # until some unrelated input happens to change.
    set(_qgc_plugin_marker_deps
        "$<TARGET_FILE:QGCPluginAPI>"
        "${_qgc_plugin_marker_script}"
        ${_qgc_plugin_marker_sdk_headers}
    )
    foreach(_qgc_plugin_marker_input IN LISTS PLUGIN_SOURCES PLUGIN_QRC_FILES PLUGIN_MANIFEST)
        if(IS_ABSOLUTE "${_qgc_plugin_marker_input}")
            list(APPEND _qgc_plugin_marker_deps "${_qgc_plugin_marker_input}")
        else()
            list(APPEND _qgc_plugin_marker_deps "${CMAKE_CURRENT_SOURCE_DIR}/${_qgc_plugin_marker_input}")
        endif()
    endforeach()

    # A .qrc's own mtime does not move when a file it embeds changes, but AUTORCC
    # rebuilds and relinks the dylib when one does — QML and SVG edits are the
    # commonest change of all in the dev loop. So the marker depends on the files
    # each .qrc lists, not merely on the .qrc. Each entry's path is relative to
    # its .qrc's directory, matching how rcc itself resolves them.
    #
    # The .qrc files also join CMAKE_CONFIGURE_DEPENDS: this list is derived at
    # configure time, so without that, a file newly added to a .qrc would not be
    # tracked until something else happened to trigger a reconfigure.
    #
    # .qrc files are collected from SOURCES as well as QRC_FILES on purpose: both
    # spellings work for building (AUTORCC keys off the extension, not the
    # keyword), so a caller that passes its .qrc in SOURCES — plugins/qdrive does
    # — must not silently lose resource tracking. Correctness here cannot depend
    # on which keyword the call site happened to choose.
    #
    # Known limitation: the extraction below is a regex, not an XML parser, so a
    # <file> element commented out inside the .qrc would still be picked up. No
    # .qrc in this tree does that, and an extra dependency is harmless anyway.
    set(_qgc_plugin_qrc_all ${PLUGIN_QRC_FILES})
    foreach(_qgc_plugin_source IN LISTS PLUGIN_SOURCES)
        # Case-insensitive, because AUTORCC's own suffix match is: a MyPlugin.QRC
        # in SOURCES would be compiled and linked by AUTORCC while a
        # case-sensitive test here silently skipped tracking its contents.
        get_filename_component(_qgc_plugin_source_ext "${_qgc_plugin_source}" LAST_EXT)
        string(TOLOWER "${_qgc_plugin_source_ext}" _qgc_plugin_source_ext)
        if(_qgc_plugin_source_ext STREQUAL ".qrc")
            list(APPEND _qgc_plugin_qrc_all "${_qgc_plugin_source}")
        endif()
    endforeach()
    if(_qgc_plugin_qrc_all)
        list(REMOVE_DUPLICATES _qgc_plugin_qrc_all)
    endif()

    foreach(_qgc_plugin_qrc IN LISTS _qgc_plugin_qrc_all)
        if(IS_ABSOLUTE "${_qgc_plugin_qrc}")
            set(_qgc_plugin_qrc_path "${_qgc_plugin_qrc}")
        else()
            set(_qgc_plugin_qrc_path "${CMAKE_CURRENT_SOURCE_DIR}/${_qgc_plugin_qrc}")
        endif()
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_qgc_plugin_qrc_path}")

        # Scanning happens at configure time, so a .qrc generated by the build
        # cannot be read here. Say that plainly instead of failing with a bare
        # "file does not exist" pointing at a line the caller never wrote.
        if(NOT EXISTS "${_qgc_plugin_qrc_path}")
            message(FATAL_ERROR
                "qgc_add_plugin(${PLUGIN_NAME}): resource file not found at configure time: "
                "${_qgc_plugin_qrc_path}. A generated .qrc cannot have its contents tracked "
                "by the build marker; list its inputs in SOURCES instead.")
        endif()

        get_filename_component(_qgc_plugin_qrc_dir "${_qgc_plugin_qrc_path}" DIRECTORY)
        file(READ "${_qgc_plugin_qrc_path}" _qgc_plugin_qrc_xml)
        string(REGEX MATCHALL "<file[^>]*>[^<]+</file>" _qgc_plugin_qrc_entries "${_qgc_plugin_qrc_xml}")
        foreach(_qgc_plugin_qrc_entry IN LISTS _qgc_plugin_qrc_entries)
            string(REGEX REPLACE "<file[^>]*>([^<]+)</file>" "\\1" _qgc_plugin_qrc_rel "${_qgc_plugin_qrc_entry}")
            string(STRIP "${_qgc_plugin_qrc_rel}" _qgc_plugin_qrc_rel)
            list(APPEND _qgc_plugin_marker_deps "${_qgc_plugin_qrc_dir}/${_qgc_plugin_qrc_rel}")
        endforeach()
    endforeach()

    add_custom_command(
        OUTPUT "${_qgc_plugin_marker_file}"
        COMMAND ${CMAKE_COMMAND} -P "${_qgc_plugin_marker_script}"
        DEPENDS ${_qgc_plugin_marker_deps}
        COMMENT "Regenerating build marker for ${PLUGIN_NAME}"
        VERBATIM
    )

    # Create the plugin as a MODULE library
    add_library(${PLUGIN_NAME} MODULE ${PLUGIN_SOURCES} ${PLUGIN_QRC_FILES} ${_qgc_plugin_marker_file})

    # The generated marker declares no Q_OBJECT and no resources. Keeping it out
    # of autogen also keeps its custom command clear of the target's *_autogen
    # utility targets, which an earlier BYPRODUCTS-based attempt cycled against
    # ("cyclic dependencies are allowed only among static libraries").
    set_source_files_properties("${_qgc_plugin_marker_file}" PROPERTIES SKIP_AUTOMOC ON SKIP_AUTORCC ON)

    # Manifest, embedded into the library via Q_PLUGIN_METADATA(... FILE "qgcplugin.json").
    # Configured into the binary dir so hostBuildId matches the host build; the binary dir
    # joins the include path below so moc can resolve the FILE reference.
    configure_file(${PLUGIN_MANIFEST} "${CMAKE_CURRENT_BINARY_DIR}/qgcplugin.json" @ONLY)
    target_include_directories(${PLUGIN_NAME} PRIVATE ${CMAKE_CURRENT_BINARY_DIR})

    # Enable Qt features
    set_target_properties(${PLUGIN_NAME} PROPERTIES
        AUTOMOC ON
        AUTORCC ON
        CXX_STANDARD 20
        CXX_STANDARD_REQUIRED ON
        LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIG>/plugins"
        RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIG>/plugins"
    )

    # Link only the published SDK + stock Qt. D2's include-boundary enforcement
    # is the build itself — with no src/ path on the include list, a plugin
    # reaching for a QGC internal fails to compile, not just to link.
    target_link_libraries(${PLUGIN_NAME} PRIVATE QGCPluginAPI)

    # Platform-specific plugin extension
    if(WIN32)
        set_target_properties(${PLUGIN_NAME} PROPERTIES SUFFIX ".dll")
    elseif(APPLE)
        set_target_properties(${PLUGIN_NAME} PROPERTIES SUFFIX ".dylib")
    else()
        set_target_properties(${PLUGIN_NAME} PROPERTIES SUFFIX ".so")
    endif()

    if(PLUGIN_NO_DEPLOY)
        message(STATUS "  Configured plugin: ${PLUGIN_NAME} (tier ${PLUGIN_TIER}, no auto-deploy)")
        return()
    endif()

    # Auto-deploy plugin to runtime location after build (for development).
    # Mirrors QGCApplication::_setInstanceInfo()'s applicationName computation
    # (src/QGCApplication.cc) exactly, so the deploy dir always matches where
    # QGCPluginLoader::defaultPluginPaths() looks at runtime for any
    # QGC_APP_NAME / QGC_ORG_NAME / QGC_STABLE_BUILD combination.
    if(QGC_STABLE_BUILD)
        set(_qgc_plugin_app_name "${QGC_APP_NAME}")
    else()
        set(_qgc_plugin_app_name "${QGC_APP_NAME} Daily")
    endif()

    if(APPLE)
        set(PLUGIN_DEPLOY_DIR "$ENV{HOME}/Library/Application Support/${QGC_ORG_NAME}/${_qgc_plugin_app_name}/plugins")
    elseif(UNIX)
        set(PLUGIN_DEPLOY_DIR "$ENV{HOME}/.local/share/${QGC_ORG_NAME}/${_qgc_plugin_app_name}/plugins")
    elseif(WIN32)
        set(PLUGIN_DEPLOY_DIR "$ENV{APPDATA}/${QGC_ORG_NAME}/${_qgc_plugin_app_name}/plugins")
    endif()

    add_custom_command(TARGET ${PLUGIN_NAME} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E make_directory "${PLUGIN_DEPLOY_DIR}"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
            $<TARGET_FILE:${PLUGIN_NAME}>
            "${PLUGIN_DEPLOY_DIR}/"
        COMMENT "Deploying ${PLUGIN_NAME} to ${PLUGIN_DEPLOY_DIR}"
    )

    message(STATUS "  Configured plugin: ${PLUGIN_NAME} (tier ${PLUGIN_TIER})")
    message(STATUS "  ${PLUGIN_NAME}: Will auto-deploy to ${PLUGIN_DEPLOY_DIR}")
endfunction()
