#!/usr/bin/env python3
"""
Derive the SDK-side artifacts of the QGroundControl.PluginUI QML module.

The module has one roster — src/PluginSystem/PluginUI/qmldir — which the running
host consumes directly as a resource. Its type entries point at the owning
module's .qml files by relative path so a plugin's type and the host's type are
literally the same URL, and therefore the same type.

A published SDK package has no host resource tree to point into, so it ships flat:
the control bodies sit beside the qmldir. This script produces that flat form
without a second hand-maintained roster:

  * the SDK qmldir     — same entries, paths reduced to bare filenames
  * the SDK .qmltypes  — the C++ types' metadata, carved out of the host build's
                         generated qmltypes with `exports:` rewritten to this URI
  * --print-sources    — the .qml bodies CMake must install, one per line

Composite (.qml) types have no generated metadata at all — Qt ships no generator
for them — which is why the bodies are packaged rather than described. They exist
in the package only to be linted against; the host supplies every implementation
at runtime.

Usage:
    python3 tools/derive_plugin_ui_sdk.py --qmldir <in> --out-qmldir <out> \
        --qmltypes <host.qmltypes> --out-qmltypes <out> \
        --cpp-type QGCPalette [--cpp-type ...]

    python3 tools/derive_plugin_ui_sdk.py --qmldir <in> --print-sources
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

GENERATED_HEADER = "# Generated by tools/derive_plugin_ui_sdk.py from src/PluginSystem/PluginUI/qmldir. Do not edit."

# Directives that may appear in a roster qmldir. Anything else on a non-comment
# line is treated as a type entry, and anything that doesn't parse as one is an
# error: silently dropping a roster line is the exact failure this file exists to
# make impossible.
_DIRECTIVES = frozenset(
    {"module", "depends", "import", "typeinfo", "prefer", "internal", "optional"}
)


@dataclass(frozen=True)
class TypeEntry:
    """One published composite type."""

    name: str
    version: str
    path: str
    singleton: bool

    @property
    def filename(self) -> str:
        return self.path.rsplit("/", 1)[-1]


@dataclass
class QmlDir:
    module: str
    entries: list[TypeEntry]
    #: Source lines from `module` onward, so tier comments survive into the package.
    body_lines: list[str]


def parse_qmldir(text: str) -> QmlDir:
    """Parse a roster qmldir. Raises ValueError on anything it can't account for."""
    module = ""
    entries: list[TypeEntry] = []
    body_lines: list[str] = []

    for lineno, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if module:
            body_lines.append(raw)
        if not line or line.startswith("#"):
            continue

        tokens = line.split()
        if tokens[0] == "module":
            if module:
                raise ValueError(f"line {lineno}: duplicate 'module' directive")
            module = tokens[1]
            body_lines.append(raw)
            continue
        if not module:
            raise ValueError(f"line {lineno}: content before the 'module' directive")
        if tokens[0] in _DIRECTIVES:
            continue

        singleton = tokens[0] == "singleton"
        if singleton:
            tokens = tokens[1:]
        if len(tokens) != 3:
            raise ValueError(f"line {lineno}: not a type entry: {line!r}")
        name, version, path = tokens
        if not re.fullmatch(r"\d+\.\d+", version):
            raise ValueError(f"line {lineno}: bad version {version!r} for type {name!r}")
        entries.append(TypeEntry(name=name, version=version, path=path, singleton=singleton))

    if not module:
        raise ValueError("no 'module' directive found")

    # The package flattens every entry into one directory, so two types drawn from
    # different source dirs under the same filename would silently ship one body
    # under both names. Catch it in the roster instead of in someone's plugin.
    _reject_duplicates("type name", [entry.name for entry in entries])
    _reject_duplicates("filename", [entry.filename for entry in entries])

    return QmlDir(module=module, entries=entries, body_lines=body_lines)


def _reject_duplicates(what: str, values: list[str]) -> None:
    seen: set[str] = set()
    for value in values:
        if value in seen:
            raise ValueError(f"duplicate {what} in the roster: {value!r}")
        seen.add(value)


def render_sdk_qmldir(qmldir: QmlDir, typeinfo: str) -> str:
    """Re-emit the roster with bare filenames, plus a typeinfo line for the C++ half."""
    out: list[str] = [GENERATED_HEADER, ""]
    for raw in qmldir.body_lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            out.append(raw)
            continue

        tokens = line.split()
        if tokens[0] == "module":
            out.append(raw)
            out.append(f"typeinfo {typeinfo}")
            continue
        if tokens[0] == "typeinfo":
            # Ours is authoritative; a roster-side one would duplicate the directive.
            continue
        if tokens[0] in _DIRECTIVES:
            out.append(raw)
            continue

        prefix = "singleton " if tokens[0] == "singleton" else ""
        name, version, path = tokens[1:] if prefix else tokens
        out.append(f"{prefix}{name} {version} {path.rsplit('/', 1)[-1]}")

    return "\n".join(out) + "\n"


def _split_components(module_body: str) -> list[str]:
    """Split a Module {} body into its top-level Component {} blocks.

    Brace counting skips over string literals — a default value or a doc string
    containing a brace would otherwise truncate the block.
    """
    blocks: list[str] = []
    depth = 0
    start = -1
    in_string = False
    escaped = False

    for index, char in enumerate(module_body):
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == "{":
            if depth == 0:
                start = module_body.rfind("Component", 0, index)
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0 and start >= 0:
                blocks.append(module_body[start : index + 1])
                start = -1
            elif depth < 0:
                raise ValueError("unbalanced braces in qmltypes Module block")

    if depth != 0:
        raise ValueError("unbalanced braces in qmltypes Module block")
    return blocks


def carve_qmltypes(text: str, names: list[str], uri: str) -> str:
    """Extract the named Components from a generated .qmltypes, retargeted at `uri`."""
    open_brace = text.find("{", text.find("Module"))
    close_brace = text.rfind("}")
    if open_brace < 0 or close_brace < open_brace:
        raise ValueError("input does not contain a Module {} block")

    wanted = list(dict.fromkeys(names))
    by_name: dict[str, str] = {}
    for block in _split_components(text[open_brace + 1 : close_brace]):
        match = re.search(r'^\s*name:\s*"([^"]+)"', block, re.MULTILINE)
        if match and match.group(1) in wanted:
            by_name[match.group(1)] = block

    missing = [name for name in wanted if name not in by_name]
    if missing:
        raise ValueError(f"types not found in the generated qmltypes: {', '.join(missing)}")

    # Scoped to the exports: line — a property's default value could otherwise
    # contain something that looks like a URI-qualified export and be rewritten.
    carved = [
        re.sub(
            r"^(\s*exports:\s*\[)(.*)(\]\s*)$",
            lambda m: (
                m.group(1)
                + re.sub(r'"[^"/]+/(\w+ \d+\.\d+)"', rf'"{uri}/\1"', m.group(2))
                + m.group(3)
            ),
            by_name[name],
            flags=re.MULTILINE,
        )
        for name in wanted
    ]
    body = "\n".join(carved)
    return (
        "import QtQuick.tooling 1.2\n"
        "\n"
        "// Generated by tools/derive_plugin_ui_sdk.py. Do not edit.\n"
        "//\n"
        "// The C++ half of the published QML contract, carved from the host build's\n"
        "// own generated metadata so the two can never describe different shapes.\n"
        "\n"
        "Module {\n"
        f"{body}\n"
        "}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--qmldir", required=True, type=Path, help="the roster qmldir to derive from"
    )
    parser.add_argument("--out-qmldir", type=Path, help="where to write the SDK qmldir")
    parser.add_argument("--qmltypes", type=Path, help="the host build's generated .qmltypes")
    parser.add_argument("--out-qmltypes", type=Path, help="where to write the carved .qmltypes")
    parser.add_argument(
        "--cpp-type",
        action="append",
        default=[],
        metavar="NAME",
        help="a C++ type to publish (repeatable); must match PluginUIModule.cc",
    )
    parser.add_argument(
        "--print-sources",
        action="store_true",
        help="print the roster's .qml paths, one per line, and exit",
    )
    args = parser.parse_args(argv)

    try:
        qmldir = parse_qmldir(args.qmldir.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"error: {args.qmldir}: {exc}", file=sys.stderr)
        return 1

    if args.print_sources:
        print("\n".join(entry.path for entry in qmldir.entries))
        return 0

    if not args.out_qmldir or not args.qmltypes or not args.out_qmltypes:
        parser.error(
            "--out-qmldir, --qmltypes and --out-qmltypes are required unless --print-sources is given"
        )
    if not args.cpp_type:
        parser.error("at least one --cpp-type is required")

    typeinfo = f"{qmldir.module}.qmltypes"
    if args.out_qmltypes.name != typeinfo:
        print(
            f"error: --out-qmltypes must be named {typeinfo} to match the qmldir's typeinfo line",
            file=sys.stderr,
        )
        return 1

    try:
        carved = carve_qmltypes(
            args.qmltypes.read_text(encoding="utf-8"), args.cpp_type, qmldir.module
        )
    except (OSError, ValueError) as exc:
        print(f"error: {args.qmltypes}: {exc}", file=sys.stderr)
        return 1

    args.out_qmldir.parent.mkdir(parents=True, exist_ok=True)
    args.out_qmldir.write_text(render_sdk_qmldir(qmldir, typeinfo), encoding="utf-8")
    args.out_qmltypes.parent.mkdir(parents=True, exist_ok=True)
    args.out_qmltypes.write_text(carved, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
